### PR TITLE
Add support to Fedora systems

### PR DESCRIPTION
**Pull request by augustoicaro**
Hello Salih,

Yesterday I changed my SO to Nobara due to my hype with linux gaming and steam deck. As Nobara is a Fedora based distro I added support to it and fixed one numpy warning and one problem in 43 that the menu wasn't opening.

I also added a workflow check for fedora :)

Thanks again for your work on this indicator.

### CODE REVIEW

**Comment by augustoicaro** [comment]
I will investigate this problem with the dbus-python installation.

**Review by salihmarangoz — CHANGES_REQUESTED** [review]
Hello Augusto,

Thanks for your PR. Maybe adding the missing package can solve this problem.

**Comment by augustoicaro** [comment]
Ok. Now the action is fixed. The problem was that the dbus system package wasn't in the image, so I added it as a dependence. I also simplified the equivalent dependencies of debian `build-essential`.

Just approve the last workflow. The other 3 were me testing in my fork.

**Review by salihmarangoz — APPROVED** [review]

**Comment by salihmarangoz** [comment]
Thank you :)

**Pull request merged**
