### PR TITLE
Improve mouse effects with ripples for scroll and click

### PR DESCRIPTION
**Pull request by augustoicaro**
Hello Salih,

Thank you for the updates! I liked the new juggling effect!

I was messing around with the new mouse + keyboard effect, and as a non-heavy mouse user, I noticed that I was missing a reaction for the mouse scroll. So I improved the mouse code to listen to the mouse scroll and click and added the ripple effect to each one.

### CODE REVIEW

**Comment by salihmarangoz** [comment]
Wow, super nice, again! Wait for my version of this :)

**Comment by salihmarangoz** [comment]
I added a better scroll effect with 0b3fcb18e1fd95157a046230754e987e34d16913 @augustoicaro :)

**Comment by augustoicaro** [comment]
I liked your version better. The shift effect combines better with the scroll. It was a clever idea to use the circles to create the background.

**Comment by augustoicaro** [comment]
@salihmarangoz , about the commit https://github.com/salihmarangoz/system_tray_extensions/commit/0b3fcb18e1fd95157a046230754e987e34d16913 , what was the bug fix? Was moving the initialization of `ripple_list` in `rgb_kb_custom/reactive_keyboard_colorful.py`? I think I didn't find it.

**Comment by salihmarangoz** [comment]
@augustoicaro , There is a rare case where `self.keyboard_mapper = KeyboardMapper(self.keyboard_cb)` may call the callback directly if a key is pressed at that time. It did happen a few times so I fixed this problem.

For `self.mouse = Controller()` it was not needed to move it. My bad :)

**Pull request merged**
